package com.artemonre.hireme.theme

import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_light_primary = Color(0xFF0B5FA5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3B)
val md_theme_light_secondary = Color(0xFF135E5E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA8F0EC)
val md_theme_light_onSecondaryContainer = Color(0xFF00201F)
val md_theme_light_tertiary = Color(0xFF8B5000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB1)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)

// Dark theme
val md_theme_dark_primary = Color(0xFF6FB2FF)
val md_theme_dark_onPrimary = Color(0xFF00284D)
val md_theme_dark_primaryContainer = Color(0xFF1E4976)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E4FF)
val md_theme_dark_secondary = Color(0xFF7FDCE0)
val md_theme_dark_onSecondary = Color(0xFF00363A)
val md_theme_dark_secondaryContainer = Color(0xFF16494D)
val md_theme_dark_onSecondaryContainer = Color(0xFFB0F0F5)
val md_theme_dark_tertiary = Color(0xFFFFB868)
val md_theme_dark_onTertiary = Color(0xFF482900)
val md_theme_dark_tertiaryContainer = Color(0xFF673C00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0A0E16)
val md_theme_dark_onBackground = Color(0xFFE4E8F5)
val md_theme_dark_surface = Color(0xFF0A0E16)
val md_theme_dark_onSurface = Color(0xFFE4E8F5)
val md_theme_dark_surfaceVariant = Color(0xFF232B3D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8DC)
val md_theme_dark_outline = Color(0xFF5C6B85)